name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ${{ github.ref == 'refs/heads/main' && 'self-hosted-production' || 'self-hosted-staging' }}
    env:
      ACTIONS_STEP_DEBUG: true
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}/client-portal:${{ github.sha }} .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}/client-portal:${{ github.sha }} \
            ${{ secrets.ECR_REPOSITORY_URI }}/client-portal:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/client-portal:${{ github.sha }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/client-portal:latest

      - name: Deploy Docker Image
        run: |
          cd /home/ubuntu/client-portal
          docker-compose down
          docker-compose up -d
