name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted  # Use your self-hosted runner
    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      # 3. Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .

      # 4. Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} \
            ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      # 1. Log in to AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      # 2. Pull Docker Image from ECR
      - name: Pull Docker Image
        run: docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # 3. Deploy Docker Image
      - name: Run Docker Container
        run: |
          docker stop client-portal || true
          docker rm client-portal || true
          docker run -d \
            --name client-portal \
            -p 5000:5000 \
            ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # 4. Verify Deployment
      - name: Check Running Containers
        run: docker ps -a
