name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # 1. Clean Workspace to Remove Stale Files
      - name: Clean Workspace
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/client-portal/
      
      # 2. Check Out the Latest Code
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full repository to avoid shallow clones

      # 3. Build Docker Image with Updated Code
      - name: Build and Push Docker Image
        run: |
          docker build -t 533267227148.dkr.ecr.eu-central-1.amazonaws.com/client-portal:${{ github.sha }} .
          docker push 533267227148.dkr.ecr.eu-central-1.amazonaws.com/client-portal:${{ github.sha }}
