name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true

    outputs:
      image_tag: ${{ steps.build_image.outputs.image_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Confirm code checkout
        run: |
          echo "Current working directory: $(pwd)"
          ls -l

      - name: Build Docker Image
        id: build_image
        run: |
          export IMAGE_TAG=${GITHUB_SHA}
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG .
        outputs:
          image_tag: $GITHUB_SHA

  push_to_ecr:
    needs: build
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Push to ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}:${IMAGE_TAG} ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

  deploy_staging:
    needs: push_to_ecr
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Staging
        run: |
          ssh -i ${{ secrets.STAGING_SSH_KEY }} ubuntu@${{ secrets.STAGING_HOST }} \
          "docker pull ${{ secrets.ECR_REPOSITORY_URI }}:${IMAGE_TAG} && docker-compose up -d"

  deploy_production:
    needs: push_to_ecr
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Production
        run: |
          ssh -i ${{ secrets.PRODUCTION_SSH_KEY }} ubuntu@${{ secrets.PRODUCTION_HOST }} \
          "docker pull ${{ secrets.ECR_REPOSITORY_URI }}:${IMAGE_TAG} && docker-compose up -d"
